# Generated by Django 3.0.10 on 2021-03-06 15:38

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('GOV', 'GOVERNMENT'), ('PRIV', 'PRIVATE INSTITUTION')], max_length=150)),
                ('status', models.CharField(choices=[('NOT OPERATIONAL', 'NOT OPERATIONAL'), ('OPERATION', 'OPERATIONAL')], max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('BASIC', 'Basic Ambulance'), ('ADVANCE', 'Advance Ambulance'), ('MORTUARY', 'Mortuary Ambulance'), ('Neonatal', 'Neonatal Ambulance'), ('Patient-Transport', 'Patient Transport Vehicle'), ('Air', 'Air Ambulance')], max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('services', models.TextField()),
                ('capacity', models.IntegerField()),
                ('request_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
        ),
    ]
