# Generated by Django 3.0.10 on 2021-03-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ENGAGED', 'ENGAGED')], default='AVAILABLE', max_length=50),
        ),
    ]
