# Generated by Django 3.0.10 on 2021-03-07 09:26

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_ambulance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [36.8219, -1.2921], 'marker_color': 'blue', 'zoom': 8}, null=True),
        ),
    ]
