# Generated by Django 3.0.10 on 2021-03-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20210307_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
