# Generated by Django 3.0.10 on 2021-03-07 10:50

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='latitude',
            field=models.CharField(default='12', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='longitude',
            field=models.CharField(default='12', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=mapbox_location_field.models.LocationField(default='ew', map_attrs={'center': [36.8219, -1.2921], 'marker_color': 'blue', 'zoom': 8}),
            preserve_default=False,
        ),
    ]
