# Generated by Django 3.0.10 on 2021-03-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20210307_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
